Code review topic revised as topic was too long.
Lordjiggyx/SQA pull request #24
Opened 2020-04-07 21:46 UTC by rmacken98

Code review topic revised and changes made due to overlap in points made and topic being too long.
Files renamed :
CRBP.md -> CodeReviewBadPractices
image002.gif -> linesofcodegraph.gif

2020-04-07 23:44 UTC, NicBoi requested changes
I think you need to move the images from "Bad_Practices/Code_Reviews/Images" to your topic folder and update the image links

2020-04-07 23:44 UTC, NicBoi commented on CodeReviews/CodeReviewBadPractices.md
>  <img src="https://miro.medium.com/max/1400/1*D9YKlFGZKiYoR57tUTpCrg.jpeg" alt="T-Shirt Size Image" width="400">
Should reference the images in the repo and modify alternative text to a more appropriate name

2020-04-07 23:44 UTC, NicBoi commented on CodeReviews/CodeReviewBadPractices.md
>  <img src="https://miro.medium.com/max/1400/1*UbeT74oIf3JlX1YRu90EKA.jpeg" alt="T-Shirt Size Image" width="400" center>
Should reference the images in the repo and modify alternative text to a more appropriate name

2020-04-08 14:00 UTC, Lordjiggyx approved these changes
Happy with this

2020-04-08 14:52 UTC, NicBoi approved these changes
Looks good, happy to merge

2020-04-08 15:10 UTC, merged